/* FILTRANDO VALORES NULOS */

SELECT NOME, SEXO, ENDERECO FROM CLIENTE WHERE EMAIL IS NULL;

SELECT NOME, SEXO, ENDERECO FROM CLIENTE WHERE EMAIL IS NOT NULL;

/* CLÁUSULA UPDATE */

UPDATE CLIENTE SET EMAIL = "LILIAN@HOTMAIL.COM"; /* ERRADO VAI MUDAR TODA TABELA */

/* WHERE - VAI SER O SEU MELHOR AMIGO PARA A VIDA INTEIRA; */

SELECT * FROM CLIENTE WHERE NOME = 'CELIA';

UPDATE CLIENTE SET EMAIL = 'CELIA@GMAIL.COM' WHERE NOME = 'CELIA'; /* FORMA CORRETA */

/* CLÁUSULA DELETE */

SELECT COUNT(*) FROM CLIENTE WHERE NOME = 'ANA';

SELECT * FROM CLIENTE WHERE NOME = 'ANA';

DELETE FROM CLIENTE WHERE NOME = 'ANA';

SELECT 6-1;

SELECT * FROM CLIENTE;

INSERT INTO CLIENTE VALUES ('CARLA','F','C.LOPES@UOL.COM',45638854,'4575-0048','RUA COPPER LEAF - WILLIAMSBURG - KITCHENER');

DELETE FROM CLIENTE WHERE NOME = 'CARLA' OR EMAIL = 'CARLA@GMAIL.COM'; -- OR TRAZ TODO MUNDO COM PELO MENOS UMA DAS CONDIÇÕES

DELETE FROM CLIENTE WHERE NOME = 'CARLA' AND EMAIL = 'CARLA@GMAIL.COM'; -- AND TRAZ OS REGISTROS QUE SATISFAÇA AS CONDIÇÕES


